[2012-09-30 23:28:28,145 django.request WARNING] base: Not Found: /favicon.ico/
[2012-09-30 23:28:38,643 django.request WARNING] base: Not Found: /favicon.ico/
[2012-09-30 23:29:08,924 django.request WARNING] base: Not Found: /favicon.ico/
[2012-09-30 23:29:13,235 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-01 09:44:07,733 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-01 09:44:09,971 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-01 09:44:13,732 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-01 09:44:17,760 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-01 09:44:17,819 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-01 09:51:42,199 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-01 09:51:42,217 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 16:26:10,576 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-03 16:26:10,659 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 16:26:18,162 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-03 16:26:18,191 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 16:26:18,339 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 16:26:22,685 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-03 16:26:22,698 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 16:26:25,215 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-03 16:26:25,237 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 16:26:27,808 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 16:26:27,875 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 18:02:20,858 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 18:08:21,552 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 18:08:47,882 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 18:20:24,274 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 18:20:24,343 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:00:15,248 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:00:17,453 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:00:20,522 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:00:32,400 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:12,239 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:16,018 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:18,948 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:20,888 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:21,867 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:26,278 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:28,204 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:40,909 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:42,171 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:45,893 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:47,678 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:48,908 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:52,456 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:01:58,384 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:02:00,355 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:02:05,535 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:02:05,767 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:02:23,300 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:02:31,368 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:29:34,789 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:46:35,039 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:48:46,669 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:51:06,577 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:53:14,756 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:53:19,085 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:53:36,005 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:54:36,254 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:54:45,786 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:54:49,171 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:54:49,195 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:55:20,139 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:58:00,688 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:58:42,799 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:58:47,475 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:58:47,605 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 19:59:14,358 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:18:10,858 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:19:25,489 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:20:24,210 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:20:47,104 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:20:50,230 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:20:57,153 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:20:59,434 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:21:04,951 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:27:59,671 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:28:05,122 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:28:08,146 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:28:11,211 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:28:14,458 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:28:14,490 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:28:16,981 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:29:17,922 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:29:58,977 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:30:33,373 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:31:46,837 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:39:51,296 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:41:21,915 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:43:48,619 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:44:24,967 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:44:47,178 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:49:13,578 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:49:17,753 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:49:17,788 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:52:45,993 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:52:46,028 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:53:29,914 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:53:30,093 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:54:10,329 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:54:10,358 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:57:37,590 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:57:37,618 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:58:40,099 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:58:40,127 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 21:58:46,273 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:01:02,499 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:09:02,334 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:09:06,386 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:09:06,418 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:09:24,081 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:09:24,108 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:09:54,276 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:09:54,298 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:10:48,304 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:31:04,819 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 22:31:04,848 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:17:53,488 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:17:53,506 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:19:52,791 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:20:34,690 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:27:40,787 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:27:43,043 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:27:46,103 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:27:48,667 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:28:50,021 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:28:52,269 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:28:54,486 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:28:57,814 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:29:00,012 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:29:33,566 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:29:35,331 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:29:38,194 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:29:44,689 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:29:52,395 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:29:55,879 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:30:08,120 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-03 23:30:51,453 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:08:57,217 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:08:57,298 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:11:38,846 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:11:43,918 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:11:46,942 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:12:05,297 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:14:22,720 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:14:41,032 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:14:44,418 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:14:48,229 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:14:48,302 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:14:56,321 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:14:56,364 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:15:17,508 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:15:17,557 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:15:24,520 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:15:24,580 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:17:36,449 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:17:36,646 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:19:39,675 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:19:39,695 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:21:33,715 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:21:33,818 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:21:43,079 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:21:45,962 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:21:48,566 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 03:21:51,904 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:02:06,971 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-04 11:02:07,049 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:11:38,923 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:11:42,020 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-04 11:11:42,033 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:11:46,251 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:11:46,270 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:11:49,760 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:12:12,574 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:13:17,976 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:13:28,909 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-04 11:13:28,940 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-06 21:41:08,353 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-06 21:41:08,430 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-06 21:41:11,717 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-06 21:41:11,727 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-06 21:41:12,358 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-06 21:41:17,632 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-06 21:41:17,645 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-06 21:41:20,791 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-06 21:41:20,803 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-06 21:41:31,743 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-06 21:41:31,797 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:28:10,162 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-07 22:28:10,216 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:28:10,348 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:28:15,324 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-07 22:28:15,335 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:32:14,257 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:32:17,773 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-07 22:32:17,786 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:32:19,387 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:32:28,807 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:32:31,238 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:32:34,656 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:32:37,403 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:34:44,728 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-07 22:34:44,745 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 03:53:14,546 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 03:59:20,880 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 03:59:20,901 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:02:37,678 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:03:41,841 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:06:50,720 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:06:50,756 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:11:30,271 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:11:42,964 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:11:43,000 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:12:54,564 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:12:54,592 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:14:26,168 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:25:29,059 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:26:54,842 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:31:13,440 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:33:59,664 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:39:17,726 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:47:37,566 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:48:20,220 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:50:05,261 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:50:19,536 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:50:19,561 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:51:05,337 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:51:05,366 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:53:48,807 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:53:48,825 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:56:10,816 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:56:10,833 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:57:16,764 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 04:57:16,816 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 05:00:42,372 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 05:00:45,873 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 05:00:45,903 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:23:07,289 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:23:07,326 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:23:21,199 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:23:25,069 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:23:25,108 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:23:56,302 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:23:58,326 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:24:00,052 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:24:06,482 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:24:13,867 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:24:16,329 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:24:17,886 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:24:20,355 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:24:20,470 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:25:01,766 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:25:01,815 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:26:36,663 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:26:38,895 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:26:39,126 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:27:21,891 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:27:21,993 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:29:35,813 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:29:39,899 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:29:42,819 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:29:50,111 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:29:50,147 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:30:15,485 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:30:15,596 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:30:31,267 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:30:31,385 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:30:56,634 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:30:56,651 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:31:28,075 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:31:31,176 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:31:31,255 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:31:42,730 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:31:45,662 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:31:45,725 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:32:31,355 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:32:36,742 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:32:38,934 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:32:41,834 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:32:41,907 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:33:50,107 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:33:50,128 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:34:18,774 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:38:29,060 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:40:37,935 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:40:41,153 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:40:41,248 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:41:19,438 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:41:19,515 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:42:27,386 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:42:38,979 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:42:39,232 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:51:58,981 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:51:59,005 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:53:04,907 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:53:04,932 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:53:46,119 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:53:46,301 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:54:30,660 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:54:30,854 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:56:12,314 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:56:12,523 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:59:02,682 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:59:02,918 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:59:52,014 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 06:59:52,048 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:01:24,771 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:01:24,796 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:03:18,092 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:03:18,299 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:03:22,271 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:04:11,105 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:04:36,650 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:04:36,716 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:06:07,369 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:06:07,658 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:06:15,095 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:06:15,170 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:07:45,880 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:07:45,918 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:09:01,370 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:09:01,406 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:09:54,668 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-08 07:09:54,699 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:46:28,135 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:46:28,211 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:47:22,642 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:47:22,657 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:47:28,260 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:47:33,565 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:47:33,581 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:52:26,742 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:52:26,785 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:52:40,243 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:52:40,302 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:52:40,516 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:52:44,739 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:52:44,750 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:52:47,908 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:52:47,921 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:52:51,758 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:52:51,811 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:53:47,333 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:54:06,222 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:54:06,249 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:56:00,977 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:56:18,384 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:56:18,502 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:56:18,530 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:56:52,748 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:56:52,775 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:56:56,963 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:57:03,850 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:57:03,910 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:57:13,058 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:57:13,271 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:57:13,340 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 11:57:16,331 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 11:57:16,434 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:25:14,825 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 12:25:14,937 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:25:14,955 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:25:53,265 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:25:57,274 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 12:25:57,330 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:28:51,480 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:31:23,726 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:31:39,678 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:31:51,218 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:34:38,102 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:34:42,050 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:34:46,902 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:34:59,009 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:35:16,231 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:35:20,277 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:35:23,169 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:35:27,159 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:35:28,585 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:36:43,340 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:36:49,621 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:01,788 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:05,123 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:06,896 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:08,813 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:10,546 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:12,051 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:13,353 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:25,601 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:26,424 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:27,780 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:33,810 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 12:37:46,088 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 13:05:11,699 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-10 13:05:11,745 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 13:05:11,762 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 13:11:20,250 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-10 13:11:22,510 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-11 03:02:29,016 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-11 03:02:29,048 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-11 03:02:36,483 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-11 03:02:41,688 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-11 03:02:54,323 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-11 03:03:03,119 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-11 03:03:07,554 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-11 03:03:07,626 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-11 03:03:12,264 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-11 03:03:12,284 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-12 18:43:40,067 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-12 18:43:40,132 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-12 22:39:03,400 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-12 22:39:03,441 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-12 22:39:09,047 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-12 22:39:09,061 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-12 22:39:13,532 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-12 22:39:13,546 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-12 22:39:16,291 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-12 22:39:46,221 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-12 22:42:40,606 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-14 17:10:15,991 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-14 17:10:16,049 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-14 17:11:12,363 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-14 17:11:16,877 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-14 17:11:16,890 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-14 17:11:19,668 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-14 17:11:49,827 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-14 17:21:23,457 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-14 17:21:23,470 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:01:48,329 django.request WARNING] base: Not Found: /report/testreport/0
[2012-10-15 05:01:48,494 django.request WARNING] base: Not Found: /report/testreport/0/
[2012-10-15 05:01:48,747 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:02:05,183 django.request WARNING] base: Not Found: /dir/report/testreport/0/
[2012-10-15 05:02:05,332 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:02:28,402 django.request WARNING] base: Not Found: /dir/report/testreport/0/
[2012-10-15 05:02:28,544 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:07:38,604 django.request WARNING] base: Not Found: /dir/report/testreport/0/
[2012-10-15 05:07:38,767 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:07:55,122 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:08:02,437 django.request WARNING] base: Not Found: /report/testreport/0/
[2012-10-15 05:08:02,720 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:08:11,218 django.request WARNING] base: Not Found: /dir/report/testreport/0/
[2012-10-15 05:08:11,356 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:08:13,159 django.request WARNING] base: Not Found: /dir/report/testreport/0
[2012-10-15 05:08:13,173 django.request WARNING] base: Not Found: /dir/report/testreport/0/
[2012-10-15 05:08:13,271 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:08:43,376 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:32:44,030 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:32:48,371 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-15 05:32:48,408 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:32:50,132 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:32:50,151 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:33:49,113 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-15 05:33:49,174 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:00:25,610 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-19 03:00:25,708 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:00:25,839 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:00:31,067 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-19 03:00:31,081 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:00:37,071 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-19 03:00:37,100 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:00:42,336 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:00:44,539 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:00:48,632 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:00:48,664 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:01:02,362 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 03:01:57,065 django.request WARNING] base: Not Found: /dir/report/region/fraservalley
[2012-10-19 03:01:58,855 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:07:33,294 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-19 05:07:33,316 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:07:39,822 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:07:43,544 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:07:49,201 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:08:06,913 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:08:08,816 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:08:25,433 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:08:54,155 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:05,408 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:12,287 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:16,342 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-19 05:09:16,358 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:18,406 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:18,477 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:25,593 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:25,617 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:35,744 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:09:35,769 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:22:23,799 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:22:29,698 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:22:52,742 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 05:22:55,891 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:09:46,847 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-19 06:09:46,865 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:09:53,585 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:00,135 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:02,632 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-19 06:10:02,646 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:04,682 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:04,709 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:05,822 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:07,581 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:07,603 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:11,761 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:13,079 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-19 06:10:13,109 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:17,602 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:25,412 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-19 06:10:32,329 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 09:48:32,609 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-26 09:48:32,708 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 09:48:36,560 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-26 09:48:36,574 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 09:48:36,912 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 09:48:41,991 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-26 09:48:42,003 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 09:48:47,850 django.request WARNING] base: Not Found: /favicon.ico
[2012-10-26 09:48:47,863 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 09:48:50,784 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 09:48:50,892 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 09:49:35,834 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 10:30:05,501 django.request ERROR] base: Internal Server Error: /
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/urls.py", line 8, in <module>
    admin.autodiscover()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/memdir/admin.py", line 7, in <module>
    class InlineHours(admin.NestedTabularInline):
AttributeError: 'module' object has no attribute 'NestedTabularInline'
[2012-10-26 10:30:06,229 django.request ERROR] base: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/urls.py", line 8, in <module>
    admin.autodiscover()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/memdir/admin.py", line 7, in <module>
    class InlineHours(admin.NestedTabularInline):
AttributeError: 'module' object has no attribute 'NestedTabularInline'
[2012-10-26 10:32:03,547 django.request ERROR] base: Internal Server Error: /
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/urls.py", line 21, in <module>
    (r'^api/v1/', include('fiber.api.urls')),
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named api.urls
[2012-10-26 10:32:03,861 django.request ERROR] base: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/urls.py", line 21, in <module>
    (r'^api/v1/', include('fiber.api.urls')),
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named api.urls
[2012-10-26 10:45:42,620 django.request ERROR] base: Internal Server Error: /
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/urls.py", line 33, in <module>
    url(r'^accounts/', include('registration.urls')),
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/registration/urls.py", line 15, in <module>
    from registration.backends.default.urls import *
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/registration/backends/default/urls.py", line 22, in <module>
    from django.views.generic.simple import direct_to_template
ImportError: No module named simple
[2012-10-26 10:45:43,100 django.request ERROR] base: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/urls.py", line 33, in <module>
    url(r'^accounts/', include('registration.urls')),
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/registration/urls.py", line 15, in <module>
    from registration.backends.default.urls import *
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/registration/backends/default/urls.py", line 22, in <module>
    from django.views.generic.simple import direct_to_template
ImportError: No module named simple
[2012-10-26 12:03:39,775 django.request ERROR] base: Internal Server Error: /
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/urls.py", line 33, in <module>
    url(r'^accounts/', include('registration.urls')),
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/registration/urls.py", line 15, in <module>
    from registration.backends.default.urls import *
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/registration/backends/default/urls.py", line 22, in <module>
    from django.views.generic.simple import direct_to_template
ImportError: No module named simple
[2012-10-26 12:03:40,085 django.request ERROR] base: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/ws_pep8/FRP/app/urls.py", line 33, in <module>
    url(r'^accounts/', include('registration.urls')),
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/registration/urls.py", line 15, in <module>
    from registration.backends.default.urls import *
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/registration/backends/default/urls.py", line 22, in <module>
    from django.views.generic.simple import direct_to_template
ImportError: No module named simple
[2012-10-26 12:54:48,673 django.request ERROR] base: Internal Server Error: /
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 116, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/vlad/ws_pep8/FRP/app/frontpage/views.py", line 6, in front_page_view
    return render(request, 'frontpage/frontpage.html', ret)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 40, in render
    context_instance = RequestContext(request, current_app=current_app)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/context.py", line 179, in __init__
    self.update(processor(request))
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/context_processors.py", line 25, in page_info
    page = Page.objects.get_by_url(url)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/managers.py", line 151, in get_by_url
    return qs.get(url__exact=url)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 371, in get
    num = len(clone)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 89, in __len__
    self._result_cache = list(self.iterator())
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 297, in iterator
    for row in compiler.results_iter():
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 770, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 825, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/util.py", line 43, in execute
    return self.cursor.execute(sql, params)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 358, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such column: fiber_page.is_public
[2012-10-26 12:54:49,361 django.request ERROR] base: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 116, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/views/generic/base.py", line 64, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/views/generic/base.py", line 85, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/views/generic/base.py", line 150, in get
    context = self.get_context_data(**kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/mixins.py", line 18, in get_context_data
    context['fiber_page'] = self.get_fiber_page()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/mixins.py", line 31, in get_fiber_page
    return self.fiber_page or Page.objects.get_by_url(self.get_fiber_page_url())
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/managers.py", line 151, in get_by_url
    return qs.get(url__exact=url)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 371, in get
    num = len(clone)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 89, in __len__
    self._result_cache = list(self.iterator())
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 297, in iterator
    for row in compiler.results_iter():
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 770, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 825, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/util.py", line 43, in execute
    return self.cursor.execute(sql, params)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 358, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such column: fiber_page.is_public
[2012-10-26 12:55:27,121 django.request ERROR] base: Internal Server Error: /
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 116, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/vlad/ws_pep8/FRP/app/frontpage/views.py", line 6, in front_page_view
    return render(request, 'frontpage/frontpage.html', ret)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 40, in render
    context_instance = RequestContext(request, current_app=current_app)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/context.py", line 179, in __init__
    self.update(processor(request))
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/context_processors.py", line 25, in page_info
    page = Page.objects.get_by_url(url)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/managers.py", line 151, in get_by_url
    return qs.get(url__exact=url)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 371, in get
    num = len(clone)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 89, in __len__
    self._result_cache = list(self.iterator())
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 297, in iterator
    for row in compiler.results_iter():
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 770, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 825, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/util.py", line 43, in execute
    return self.cursor.execute(sql, params)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 358, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such column: fiber_page.is_public
[2012-10-26 12:55:27,502 django.request ERROR] base: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 116, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/views/generic/base.py", line 64, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/views/generic/base.py", line 85, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/views/generic/base.py", line 150, in get
    context = self.get_context_data(**kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/mixins.py", line 18, in get_context_data
    context['fiber_page'] = self.get_fiber_page()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/mixins.py", line 31, in get_fiber_page
    return self.fiber_page or Page.objects.get_by_url(self.get_fiber_page_url())
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/managers.py", line 151, in get_by_url
    return qs.get(url__exact=url)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 371, in get
    num = len(clone)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 89, in __len__
    self._result_cache = list(self.iterator())
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/query.py", line 297, in iterator
    for row in compiler.results_iter():
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 770, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 825, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/util.py", line 43, in execute
    return self.cursor.execute(sql, params)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 358, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such column: fiber_page.is_public
[2012-10-26 13:01:20,381 django.request ERROR] base: Internal Server Error: /
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 189, in get_response
    response = middleware_method(request, response)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/middleware.py", line 54, in process_response
    t = loader.get_template('fiber/admin.html')
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1261, in url
    viewname = parser.compile_filter(bits[1])
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 353, in compile_filter
    return FilterExpression(token, self)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 570, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ':index' from 'admin:index'
[2012-10-26 13:01:20,726 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 13:05:51,095 django.request ERROR] base: Internal Server Error: /
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 189, in get_response
    response = middleware_method(request, response)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/middleware.py", line 81, in process_response
    self.get_header_html(request),
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/fiber/middleware.py", line 164, in get_header_html
    return t.render(c)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 420, in render
    raise e
NoReverseMatch: Reverse for '' with arguments '()' and keyword arguments '{}' not found.
[2012-10-26 13:05:51,435 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 13:17:46,896 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 13:17:54,699 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 13:17:58,044 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 13:17:59,935 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 13:19:44,405 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 14:34:49,188 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 15:58:32,825 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 15:59:10,383 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 15:59:47,231 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 15:59:49,466 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:00:25,567 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:00:28,794 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:00:33,007 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:01:44,501 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:02:48,620 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:02:48,777 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:03:01,395 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:03:04,873 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:03:20,647 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:03:31,038 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:03:35,894 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:03:56,954 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:04:03,110 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:04:20,062 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:04:23,053 django.request ERROR] base: Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 116, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/views.py", line 50, in __call__
    return self.create_response()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/views.py", line 131, in create_response
    (paginator, page) = self.build_page()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/views.py", line 108, in build_page
    self.results[start_offset:start_offset + self.results_per_page]
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/query.py", line 241, in __getitem__
    self._fill_cache(start, bound)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/query.py", line 140, in _fill_cache
    results = self.query.get_results(**kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/backends/__init__.py", line 469, in get_results
    self.run(**kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/backends/__init__.py", line 390, in run
    results = self.backend.search(final_query, **search_kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/backends/__init__.py", line 47, in wrapper
    return func(obj, query_string, *args, **kwargs)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 260, in search
    self.setup()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 111, in setup
    self.content_field_name, self.schema = self.build_schema(self.site.all_searchfields())
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 163, in build_schema
    raise SearchBackendError("No fields were found in any search_indexes. Please correct this before attempting to search.")
SearchBackendError: No fields were found in any search_indexes. Please correct this before attempting to search.
[2012-10-26 16:04:23,467 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:53:31,963 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:53:41,523 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:53:45,079 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:53:48,779 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:53:53,336 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:53:57,877 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:54:07,038 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:54:17,191 django.request ERROR] base: Internal Server Error: /dir/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 141, in get_response
    response = response.render()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 420, in render
    raise e
NoReverseMatch: Reverse for '' with arguments '()' and keyword arguments '{}' not found.
[2012-10-26 16:54:17,977 django.request WARNING] base: Not Found: /directory/
[2012-10-26 16:54:18,177 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 16:54:21,998 django.request ERROR] base: Internal Server Error: /dir/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 141, in get_response
    response = response.render()
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 420, in render
    raise e
NoReverseMatch: Reverse for '' with arguments '()' and keyword arguments '{}' not found.
[2012-10-26 16:54:22,761 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 17:00:42,701 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 17:00:54,204 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 17:00:56,893 django.request ERROR] base: Internal Server Error: /dir/report/region/fraservalley/
Traceback (most recent call last):
  File "/home/vlad/env/django15a1/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 116, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/vlad/ws_pep8/FRP/app/memdir/views.py", line 153, in report_region_pdf
    return report_pdf(request, 'provincial-listing', 0, locals())
  File "/home/vlad/ws_pep8/FRP/app/memdir/views.py", line 120, in report_pdf
    renderer.run()
  File "/home/vlad/ws_pep8/FRP/app/appy/pod/renderer.py", line 396, in run
    self.finalize()
  File "/home/vlad/ws_pep8/FRP/app/appy/pod/renderer.py", line 537, in finalize
    output = self.callOpenOffice(resultOdtName, resultType)
  File "/home/vlad/ws_pep8/FRP/app/appy/pod/renderer.py", line 480, in callOpenOffice
    raise pe
PodError: Extension of result file is "pdf". In order to perform conversion from ODT to this format we need to call OpenOffice. But the Python interpreter which runs the current script does not know UNO, the library that allows to connect to OpenOffice in server mode. If you can't install UNO in this Python interpreter, you can specify, in parameter "pythonWithUnoPath", the path to a UNO-enabled Python interpreter. One such interpreter may be found in <open_office_path>/program.
[2012-10-26 17:00:57,331 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 17:00:59,108 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 17:01:00,738 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 17:01:04,591 django.request WARNING] base: Not Found: /favicon.ico/
[2012-10-26 17:01:05,496 django.request WARNING] base: Not Found: /favicon.ico/
